<?php

namespace Saharin\Component\Translator\Administrator\Controller;

defined('_JEXEC') or die;

use Joomla\CMS\Factory;
use Joomla\CMS\Language\Text;
use Joomla\CMS\MVC\Model\BaseDatabaseModel;
use Joomla\CMS\Router\Route;
Use Joomla\CMS\MVC\Controller\FormController;
use Saharin\Component\Translator\Administrator\Helper\TranslatorHelper;
use Saharin\Component\Translator\Administrator\Model\FileModel;
use Joomla\CMS\Session\Session;

class FileController extends FormController
{

	/**
	 * @param   string  $name
	 * @param   string  $prefix
	 * @param   array   $config
	 *
	 * @return BaseDatabaseModel|FileModel
	 *
	 * @since version
	 */
	public function getModel($name = 'File', $prefix = 'Administrator', $config = ['ignore_request' => true])
	{
		return parent::getModel($name, $prefix, $config); // TODO: Change the autogenerated stub
	}

	public function cancel($key = null)
	{
		$this->checkToken('post', false) or die('Error Token');
		$this->setRedirect(Route::_('index.php?option=' . $this->option . '&view=' . $this->view_list, false));

		return true;
	}

	public function save($key = null, $urlVar = null)
	{
		$this->checkToken('post', false) or die('Error Token');

		$app   = Factory::getApplication();
		$model = $this->getModel();
		$data  = $this->input->post->get('jform', array(), 'array');
		$form  = $model->getForm($data, false);
		if (!$form)
		{
			$app->enqueueMessage($model->getError(), 'error');

			return false;
		}
		$validData = $model->validate($form, $data);
		if ($validData === false)
		{
			// Get the validation messages.
			$errors = $model->getErrors();

			// Push up to three validation messages out to the user.
			for ($i = 0, $n = count($errors); $i < $n && $i < 3; $i++)
			{
				if ($errors[$i] instanceof \Exception)
				{
					$app->enqueueMessage($errors[$i]->getMessage(), 'warning');
				}
				else
				{
					$app->enqueueMessage($errors[$i], 'warning');
				}
			}
			$this->setRedirect(Route::_('index.php?option=' . $this->option . '&view=' . $this->view_item . '&layout=edit', false));

			return false;
		}

		try
		{
			$file = $model->save($validData);

			$exists = $model->getState('file_exists', false);

			$this->setRedirect(Route::_('index.php?option=' . $this->option . '&view=constants&file=' . $file, false), Text::_(($exists ? 'COM_TRANSLATOR_FILE_ALREADY_EXIST' : 'COM_TRANSLATOR_FILE_ADDED')));
		}
		catch (\Exception $e)
		{
			$this->setRedirect(Route::_('index.php?option=' . $this->option . '&view=' . $this->view_list, false), $e->getMessage(), 'error');

			return false;
		}

		return true;

	}


	public function reSave()
	{
		$this->checkToken('post', false) or die('Error Token');
		$cid   = $this->input->get('cid', [], 'array');
		$model = $this->getModel();
		$model->reSave($cid);
		$this->setRedirect(Route::_('index.php?option=' . $this->option . '&view=' . $this->view_list, false))->redirect();
	}

	public function create()
	{
		$this->checkToken('get', false) or die('Error Token');
		$file = $this->input->get->get('file', null, 'raw');
		try
		{
			if (empty($file))
			{
				throw new \Exception(Text::_('COM_TRANSLATOR_MISSING_FILE'));
			}

			$fileExpl = explode(':', $file);

			if ($fileExpl[0] !== 'administrator' && $fileExpl[0] !== 'site')
			{
				throw new \Exception(Text::_('COM_TRANSLATOR_UNKNOWN_CLIENT'));
			}

			if (empty($fileExpl[1]))
			{
				throw new \Exception(Text::_('COM_TRANSLATOR_LANGUAGE_EMPTY'));
			}

			if (empty($fileExpl[2]))
			{
				throw new \Exception(Text::_('COM_TRANSLATOR_FILENAME_EMPTY'));
			}

			if ($fileExpl[0] === 'site')
			{
				$client = 1;
			}
			else
			{
				$client = 0;
			}

			$data = [];

			$data['language']  = $fileExpl[1] . $client;
			$data['extension'] = TranslatorHelper::getExtension($fileExpl[2]);


			if (stristr($fileExpl[2], '.sys') === false)
			{
				$data['sys'] = 0;
			}
			else
			{
				$data['sys'] = 1;
			}

			$this->input->post->set('jform', $data);
			$this->input->post->set(Session::getFormToken(), '1');

			$this->save();
		}
		catch (\Exception $e)
		{
			$this->setRedirect(Route::_('index.php?option=' . $this->option . '&view=' . $this->view_list, false), $e->getMessage(), 'error')->redirect();
		}
	}


}